### ISSUE TITLE
risk of burning out the P0.31 pin ( 32 , PIN_VBAT )

### ISSUE THREAD

**Issue by AdamM68** [honvl/Seeed-Xiao-NRF52840-Battery#1]
There is a comment on Xiao wiki :
_Q3: What are the considerations when using XIAO nRF52840 (Sense) for battery charging?​
When P0.14 (D14) turns off the ADC function at a high level of 3.3V, P0.31 will be at the input voltage limit of 3.6V. There is a risk of burning out the P0.31 pin. 
Currently for this issue, we recommend that users do not turn off the ADC function of P0.14 (D14) or set P0.14 (D14) to high during battery charging._

According to this suggestions we should add a procedure to allow battery measurement only when NOT charging.
During charging,  the function GetBatteryVolatge should return 0 or error.

something like 

float Xiao::GetBatteryVoltage() {

if (  !digitalRead(BAT_CHARGE_STATE) == LOW ) {
  digitalWrite(VBAT_ENABLE, LOW);
  uint32_t adcCount = analogRead(PIN_VBAT);
  float adcVoltage = adcCount * VBAT_MV_PER_LBS;
  float vBat = adcVoltage * (1510.0 / 510.0);
  digitalWrite(VBAT_ENABLE, HIGH);
  return vBat;
}
else { return 0;}
}

bool Xiao::IsChargingBattery() { return digitalRead(BAT_CHARGE_STATE) == LOW; }

**Comment by honvl** [comment]
When the USB is connected, the battery is always charging. Then, to have the serial monitor return 0 instead of the voltage from the GetBatteryVoltage function would not be useful. Secondly, not knowing the battery voltage while charging is also not useful.

**Comment by AdamM68** [comment]
anyway - the function GetBatteryVoltage seems not safe during battery charging.

**Comment by AdamM68** [comment]
The comment should be:
" During charging always set P0.14(VBAT_ENABLE) to LOW before attempting to read voltage from P0.31(PIN_VBAT) "

... so the code looks ok. 
No need to add my suggestion from first comment unless You read PIN_VBAT with VBAT_ENABLE set to LOW.  
![xiao nrf52840 battery charge](https://user-images.githubusercontent.com/41963786/232038236-aac8bbd8-402f-4991-885d-2eaabdf2f876.png)
